script: true
install: true
notifications:
  hipchat:
    template:
    - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'
    rooms:
    - b7098c17bc3283dc7ca388b68e3ca3@m3
    format: html
language: python
deploy:
  provider: pypi
  password:
    secure: !!! Получить password secure !!!
  on:
    tags: true
    all_branches: true
  distributions: sdist
  user: bars-travis
python:
- "2.7"
