script: true
install: true
language: python
python:
- '2.7'

deploy:
  provider: pypi
  server: http://pypi.bars-open.ru/
  user: fred
  password:
    secure: 2cdgCGEMCvfVYnKME2RVmsPXfWFLZ13sGjV8YNbEJMVxCZgMDh1dBznRk/1NcaqrbxMCFWxm8v6qfCsMYrbuG1hn256xkyCBYyOKmwLyeJCmjhvK6qfmeE//+7Fcv+6/MkdIwvdf3FGR8XPp691TkylIwI7BteIG+g0l+yjBLpCry1hij6ZPWaMC4WynM9MQuOh64bVLw7u7a4K6a/HWSyT+Rl+9Ge5Bl82dYekjWZ9jQpjrCVDIWYx9IkeS6GYFQ9bVYMmVHlJL4i/EmGLQh+IUfuQBWJCBeJwKA3+H2Da0cU5ciB5E+nxJ8EdvnlXk2HtN55HqgW5F1dkiAOqeVaUJPJsRD0Bs1Qcdk8ShaGog8E4OTVNteWWvlkvy5semYVIUPAMTBdwtx4V6PjghKRdYBkS53ln1TySzCHtrDTd6escsI/rCF6djzRVdx5sdE2n6F2djfUQw9ZrXi+VXwJPylvLH6KWYWaJXYpQH2JStCHKfc5wTO6c5rGSHiXKP39ZajQbIJVXuXnyn0oBVHXIwSRlhCtqSIfRK+/zC99xphNTaneAo5udEJMXAKrEGRSROxrAAVRh4qyFRjTJ+ytrDsXgh4XLIeRl77kZH/77+3tlBYznEYebQU6N2LFpOfD/tvtXs9+6udyRa66uZLOwSCsekdrQMN2tEgW40l5k=
  on:
    tags: true
  distributions: sdist

notifications:
  email:
    recipients:
    - dev-py@bars-open.ru
